USE BibleStudy;
GO

IF OBJECT_ID(N'dbo.VerseTag') IS NULL
BEGIN
	CREATE TABLE VerseTag (
		Id      INT NOT NULL,
		VerseId INT NOT NULL,
		TagId   INT NOT NULL,
		CONSTRAINT PK_VerseTag PRIMARY KEY CLUSTERED (Id ASC)
	);

	ALTER TABLE VerseTag WITH CHECK ADD CONSTRAINT FK_VerseTag_Verse FOREIGN KEY(VerseId)
	REFERENCES dbo.Verse (Id);

	ALTER TABLE VerseTag WITH CHECK ADD CONSTRAINT FK_VerseTag_Tag FOREIGN KEY(TagId)
	REFERENCES dbo.Tag (Id);
END;