USE $DbName$;
GO

IF OBJECT_ID(N'FK_VerseTag_Verse') IS NULL
BEGIN
	ALTER TABLE VerseTag WITH CHECK ADD CONSTRAINT FK_VerseTag_Verse FOREIGN KEY(VerseId)
	REFERENCES dbo.Verse (Id);
END;

IF OBJECT_ID(N'FK_VerseTag_Tag') IS NULL
BEGIN
	ALTER TABLE VerseTag WITH CHECK ADD CONSTRAINT FK_VerseTag_Tag FOREIGN KEY(TagId)
	REFERENCES dbo.Tag (Id);
END;